//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radio
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public int IsComplete { get; set; }
        public string ListeningUser { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> TrackListID { get; set; }
    }
}
