//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SongListEntities : DbContext
    {
        public SongListEntities()
            : base("name=SongListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlaylistName> PlaylistNames { get; set; }
        public virtual DbSet<TrackList> TrackLists { get; set; }
        public virtual DbSet<PlayCount> PlayCounts { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<PlayedSong> PlayedSongs { get; set; }
        public virtual DbSet<SkippedSong> SkippedSongs { get; set; }
        public virtual DbSet<CompleteAlbumListen> CompleteAlbumListens { get; set; }
        public virtual DbSet<MostPlayedArtist> MostPlayedArtists { get; set; }
        public virtual DbSet<MostUnfinishedSong> MostUnfinishedSongs { get; set; }
        public virtual DbSet<LongestSong> LongestSongs { get; set; }
        public virtual DbSet<CompleteAlbumListensByArtist> CompleteAlbumListensByArtists { get; set; }
        public virtual DbSet<CompleteAlbumListensByGenre> CompleteAlbumListensByGenres { get; set; }
    }
}
