//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackList
    {
        public string Artist { get; set; }
        public string Album { get; set; }
        public string Title { get; set; }
        public Nullable<int> TrackNumber { get; set; }
        public string Duration { get; set; }
        public string Genre { get; set; }
        public Nullable<int> PlayCount { get; set; }
        public string Location { get; set; }
        public string Username { get; set; }
        public int ID { get; set; }
        public string Art { get; set; }
        public byte[] ArtWork { get; set; }
        public string Covers { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<System.DateTime> TimeAdded { get; set; }
    }
}
